services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://mingma:ming@cluster0.08gnrvm.mongodb.net/students

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backend/.env:/app/.env 

volumes:
  mongo-data: